### ISSUE TITLE
Incorrect Method Name

### ISSUE THREAD

**Issue by adhibhuta** [xpring-eng/xpring4j#275]
As per this https://github.com/xpring-eng/xpring4j#xrppayidclient the method name is `xrpAddressForPayID` but the actual method name is `xrpAddressForPayId`

The last d is the problem.

**Comment by intelliot** [comment]
Thank you for reporting this issue. Xpring4j is no longer maintained. For Java XRPL support please see https://github.com/xrplf/xrpl4j
