### ISSUE TITLE
getBalance in the readme seem to be incorrect

### ISSUE THREAD

**Issue by guykatz** [xpring-eng/xpring4j#3]
Hi;
the example for getting balance from a wallet does not seem to be correct.
the 'address' variable is never used.
I assume this:
`
String address = "rHsMGQEkVNJmpGWs8XUBoTBiAAbwxZN5v3";
BigInteger balance = xpringClient.getBalance(XRPL_ADDRESS);
` 
should be like this:
`
String address = "rHsMGQEkVNJmpGWs8XUBoTBiAAbwxZN5v3";
BigInteger balance = xpringClient.getBalance(address);
`

**Comment by keefertaylor** [comment]
Thanks for pointing this out and apologies our documentation is a bit rough around the edges. I'll merge a fix shortly.
