### ISSUE TITLE
Unable to send XRP using XrpClient

### ISSUE THREAD

**Issue by blockchain-app12** [xpring-eng/xpring4j#364]
Hi 
I have using XrpClient but I have to face some issues
 while sending XRP payments.
I have attached the ERROR Log file.  
[java.txt](https://github.com/xpring-eng/xpring4j/files/5472978/java.txt)
Kindly support us.

**Comment by intelliot** [comment]
For sending XRP, I recommend using [xrpl4j](https://github.com/XRPLF/xrpl4j) instead.

Here is an integration test that shows an example of sending an XRP payment: https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/SubmitPaymentIT.java

**Comment by PavelNiedoba** [comment]
> For sending XRP, I recommend using [xrpl4j](https://github.com/XRPLF/xrpl4j) instead.
> 
> Here is an integration test that shows an example of sending an XRP payment: https://github.com/XRPLF/xrpl4j/blob/main/xrpl4j-integration-tests/src/test/java/org/xrpl/xrpl4j/tests/SubmitPaymentIT.java

Why would you suggest using other library to send tx when this README says its supported ? 

> An XrpClient can send XRP to other accounts on the XRP Ledger.

**Comment by intelliot** [comment]
Xpring4j should work. But [xrpl4j](https://github.com/XRPLF/xrpl4j) is newer, works better, and is actively being maintained.

As for the specific error mentioned here, I've reviewed it and I personally don't understand it. If you really want to use Xpring4j, hopefully someone else can help. But I still think you'll have a better experience with xrpl4j.
