### ISSUE TITLE
Can't get artifacts from maven 

### ISSUE THREAD

**Issue by smelis** [xpring-eng/xpring4j#5]
I've setup my username and a Personal Acces Token (PAT) in ~/.m2/settings.xml as described here:

https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry#authenticating-to-github-package-registry

And have added the repository, as per the README, to my project's pom.xml..

```
<repositories>
  <repository>
    <id>github</id>
    <name>GitHub xpring-eng Apache Maven Packages</name>
    <url>https://maven.pkg.github.com/xpring-eng</url>
  </repository>
</repositories>
```

Yet I'm still unable to retrieve the artifacts from the repo, using this dependency in the pom.
```        
<dependency>
  <groupId>io.xpring</groupId>
  <artifactId>xpring4j</artifactId>
  <version>1.0-SNAPSHOT</version>
</dependency>
```

I keep getting (variations of): 

"Could not find artifact io.xpring:xpring4j:jar:1.0 in central (https://repo1.maven.org/maven2)"

I've tried disabling the central repo, granting more access rights to the PAT, changing the version (1.0, 1.0-SNAPSHOT) but nothing seems to work.

What am I doing wrong? What am I missing?

**Comment by smelis** [comment]
Additional info...

Requested and got access to Github's Pacakge Registry beta. Does not fix the issue.

Found https://github.com/xpring-eng/xpring4j/packages/30391 which has an invalid groupId.

My guess is that my issue could be due to a mis-configuration of the part that publishes the jar/pom to the GitHub Package Registry or a bug therein (it is still in beta, I see, so it would make sense). 

Another thing I noticed is that "1.0-snapshot" is written in lowercase on the aforementioned package descriptor page, but is in uppercase in other parts of your documentation. I believe uppercase to be the default.

**Comment by keefertaylor** [comment]
Hi, 

We've been looking at this all morning and we're somewhat confused as well. We're leaning towards there being a bug in GitHub as well. Sorry that this has been a time sink. 

We're going to try to get this hosted on SonaType, but it will take a few days. In the meantime, the best way to do this is probably to download and build from source.

**Comment by smelis** [comment]
Hi,

Building from source is proving to be a bit harder than I had gathered from the README:

![image](https://user-images.githubusercontent.com/621584/66356818-c4435e80-e96c-11e9-8694-917e7ba4ed8c.png). 

I'm having trouble getting the xpring4j project to build.
I'm new to graal, and protobuf, but I'm guessing I'm missing some classes that ought to be generated from the javascript source? Not sure how to do that.

![image](https://user-images.githubusercontent.com/621584/66356922-2734f580-e96d-11e9-9377-d27ee221707b.png)

**Comment by keefertaylor** [comment]
These files are generated as part of the build process. Have you tried building? 

Could you try running `mvn clean install` on the command line?

**Comment by keefertaylor** [comment]
Separately, we're working on getting coordinates for Maven Central set up, you can monitor our progress here: https://issues.sonatype.org/browse/OSSRH-52163

**Comment by smelis** [comment]
Thanks for getting back to me. I feel a bit ashamed, but my trouble with building was actually due to my not actually building. Apparently intellij's "build project" does not kick off a mvn clean install :/. I'm used to netbeans, which does do that. 

Anyway, after adjusting the protocExecutable variable to my own location, and running mvn from the cmdline, it has built

```
[INFO] BUILD SUCCESS
```

**Comment by keefertaylor** [comment]
Awesome. Sincere apologies that this took so much back and forth to resolve and thanks for sticking with it! Please let us know what features you'd like to see added or if you have any other trouble!

I'll ping back here when we have this set up on Maven Central.

**Comment by smelis** [comment]
It's really no trouble. As for features, I would have to start playing around with the code first, but my own little xrpl4j project (https://github.com/smelis/xrpl4j) uses the websocket connection and hence can be used to subscribe to the ledger's streams, and it would be nice if this was possible from xpring4j too (eventhough it would make my own project somewhat redundant). 

Do you want me to reopen the issue until sonatype bureaucracy has been cleared?

**Comment by smelis** [comment]
But tbh, I haven't looked at whether this is part of xpring4j already...

**Comment by keefertaylor** [comment]
There should now be a consumable artifact in Maven. I have updated the README accordingly.
